services:
  mysqldb:
    container_name: livrosdavida
    image: mysql
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=livrosdavida
    volumes:
      - ./database:/var/lib/mysql